name: Code Quality

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    code-checks:
        name: Code Checks
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --immutable

            - name: Generate Panda CSS
              run: yarn prepare

            - name: Check formatting
              run: yarn format:check

            - name: Run ESLint
              run: yarn lint

            - name: Check TypeScript
              run: yarn typecheck
